### ISSUE TITLE
Please add more explanation

### ISSUE THREAD

**Issue by davidrios** [Gerkiz/Spiderissmo#1]
Hi.

Could you please add some more information about what this mod does? I really don't understand what "adds a surface to cars" means. What's that exactly? Why is it useful?

Thanks!

**Comment by Coolcatt5000** [comment]
This means when you enter a car or other vehicle (works on the modded ones I use also) you enter a separate section of the map, and can build inside of it and push items in and out of the trunk using chests, the reason they used the term "surface" is because each separate section of the map is actually another layer or dimension in the game and are referred to as a "surface".

**Comment by davidrios** [comment]
Ohhh I see! Thank you.
